x=str(input("enter something"))
length=len(x)
cap=x.capitalize()
a=x.isalnum()
b=x.isalpha()
c=x.isdigit()
d=x.lower()
e=x.upper()
f=x.replace('a','aa')
g='***'.join(x)
h=x.split()
print("length",length)
print("Cap[italise:",cap)
print("isnum",a)
print("isalphabet:",b)
print("isdigit:",c)
print("lower case:",d)
print("upper case:",e)
print("replaced:",f)
print("joined:",g)
print("splitted",h)